import { useState, useEffect } from 'react';
import { Shield, AlertTriangle, Scale, Users, Link, Ban, FileText, MapPin, Mail } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';

const DisclaimerPopup = () => {
  const [isOpen, setIsOpen] = useState(true); // Show on load
  const [isButtonVisible, setIsButtonVisible] = useState(false);

  useEffect(() => {
    // Show button after a short delay with animation
    const timer = setTimeout(() => setIsButtonVisible(true), 500);
    
    // Close disclaimer when clicking anywhere
    const handleClickAnywhere = () => {
      setIsOpen(false);
    };
    
    // Add listener after a small delay to prevent immediate close
    const listenerTimer = setTimeout(() => {
      document.addEventListener('click', handleClickAnywhere, { once: true });
    }, 100);
    
    return () => {
      clearTimeout(timer);
      clearTimeout(listenerTimer);
      document.removeEventListener('click', handleClickAnywhere);
    };
  }, []);

  return (
    <>
      {/* Floating Disclaimer Button - Animated Popup */}
      <div
        className={`fixed bottom-4 right-4 z-50 transition-all duration-500 ${
          isButtonVisible 
            ? 'opacity-100 translate-y-0' 
            : 'opacity-0 translate-y-4 pointer-events-none'
        }`}
      >
        <Button
          onClick={() => setIsOpen(true)}
          variant="outline"
          size="sm"
          className="bg-card/95 backdrop-blur-sm border-border shadow-lg hover:shadow-xl transition-all duration-300 gap-2 animate-pulse hover:animate-none"
        >
          <Shield size={14} className="text-primary" />
          <span className="text-xs font-medium">Disclaimer</span>
        </Button>
      </div>

      {/* Full Disclaimer Dialog */}
      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogContent className="max-w-3xl max-h-[85vh] p-0 overflow-hidden">
          <DialogHeader className="px-6 pt-6 pb-4 border-b border-border bg-muted/30">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-full bg-primary/10">
                <Scale className="h-5 w-5 text-primary" />
              </div>
              <div>
                <DialogTitle className="text-xl font-bold">LegalCareAI.com – DISCLAIMER</DialogTitle>
                <p className="text-sm text-muted-foreground mt-1">Effective Date: January 3, 2026</p>
              </div>
            </div>
          </DialogHeader>
          
          <ScrollArea className="h-[60vh] px-6 py-4">
            <div className="space-y-6 text-sm leading-relaxed">
              {/* Introduction */}
              <p className="text-muted-foreground">
                Welcome to LegalCareAI.com ("we," "us," "our," or the "Website"). LegalCareAI is an AI-powered legal information and community platform designed to help users understand, discuss, and explore legal concepts, documents, and questions. By accessing or using our Website, services, features, or AI tools, you agree to the following terms.
              </p>

              {/* Section 1 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4 text-destructive" />
                  <h3 className="font-semibold text-base">1. NO LEGAL ADVICE</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>
                    All content, information, responses, documents, analyses, discussions, and materials provided by LegalCareAI — whether generated by AI, community users, or staff — are provided for <strong className="text-foreground">general informational and educational purposes only</strong>.
                  </p>
                  <p>
                    The content does not constitute legal advice and should not be relied upon as a substitute for consultation with a qualified, licensed attorney or legal professional.
                  </p>
                  <ul className="list-disc pl-4 space-y-1">
                    <li>LegalCareAI does not provide legal opinions tailored to your specific situation</li>
                    <li>Laws vary by jurisdiction and facts matter — what may be appropriate in one case or place may not be appropriate in another</li>
                    <li>Do not act or refrain from acting based on any information on this Website without seeking competent legal counsel regarding your specific circumstances</li>
                  </ul>
                </div>
              </section>

              {/* Section 2 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <Users className="h-4 w-4 text-primary" />
                  <h3 className="font-semibold text-base">2. NO ATTORNEY-CLIENT RELATIONSHIP</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>
                    Your use of this Website, AI tools, discussion pages, community pages, or interactions with any content on LegalCareAI <strong className="text-foreground">does not create an attorney-client relationship</strong> between you and LegalCareAI, its operators, contributors, or any third parties.
                  </p>
                  <p>
                    No content on this Website is meant to replace or substitute professional legal advice. A professional legal relationship can only be formed through direct engagement with a licensed attorney pursuant to an agreement that explicitly establishes such a relationship.
                  </p>
                </div>
              </section>

              {/* Section 3 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <FileText className="h-4 w-4 text-amber-500" />
                  <h3 className="font-semibold text-base">3. ACCURACY, COMPLETENESS, & LIMITATIONS</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>
                    While we strive to provide accurate and current information, LegalCareAI makes <strong className="text-foreground">no warranties or guarantees</strong> whatsoever regarding the accuracy, completeness, reliability, suitability, or timeliness of any content or tool on the Website.
                  </p>
                  <p>AI-generated outputs can be:</p>
                  <ul className="list-disc pl-4 space-y-1">
                    <li>Incorrect or factually inaccurate</li>
                    <li>Incomplete or missing critical information</li>
                    <li>Outdated due to changes in law</li>
                    <li>Biased based on training data</li>
                    <li>Misinterpreted or taken out of context</li>
                    <li>Inconsistent across different queries</li>
                  </ul>
                  <p className="font-medium text-foreground">
                    You acknowledge and agree that any reliance on content or outputs from this Website is at your own risk.
                  </p>
                </div>
              </section>

              {/* Section 4 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <Users className="h-4 w-4 text-blue-500" />
                  <h3 className="font-semibold text-base">4. AI & COMMUNITY CONTENT</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>
                    LegalCareAI uses artificial intelligence and contributions from community members. AI responses and community content:
                  </p>
                  <ul className="list-disc pl-4 space-y-1">
                    <li>Are not reviewed by licensed legal professionals (unless explicitly stated)</li>
                    <li>May reflect general patterns or common interpretations</li>
                    <li>May not apply to your unique circumstances</li>
                    <li>May contain errors, omissions, or outdated information</li>
                    <li>Should not be used as the sole basis for legal decisions</li>
                  </ul>
                  <p>
                    You should treat AI or community discussions as <strong className="text-foreground">starting points for learning</strong>, not as actionable legal strategies or advice.
                  </p>
                </div>
              </section>

              {/* Section 5 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <Link className="h-4 w-4 text-green-500" />
                  <h3 className="font-semibold text-base">5. THIRD-PARTY LINKS & RESOURCES</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>
                    This Website may contain links to third-party websites, resources, documents, tools, or services for convenience. LegalCareAI:
                  </p>
                  <ul className="list-disc pl-4 space-y-1">
                    <li>Does not control third-party content</li>
                    <li>Is not responsible for any third-party materials</li>
                    <li>Does not endorse or guarantee the accuracy of any linked content</li>
                    <li>Is not liable for any damages arising from third-party content</li>
                  </ul>
                  <p>Your use of linked content is subject to the terms of the provider of that content.</p>
                </div>
              </section>

              {/* Section 6 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <Ban className="h-4 w-4 text-destructive" />
                  <h3 className="font-semibold text-base">6. LIMITATION OF LIABILITY</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>To the fullest extent permitted by applicable law:</p>
                  <p>
                    LegalCareAI and its officers, directors, employees, agents, contributors, service providers, partners, and licensors are <strong className="text-foreground">not liable for any damages</strong> arising out of or in connection with your use of this Website, any content supplied, community interactions, or decisions made based on such content.
                  </p>
                  <p>This includes, but is not limited to:</p>
                  <ul className="list-disc pl-4 space-y-1">
                    <li>Direct, indirect, incidental, special, punitive, exemplary, or consequential damages</li>
                    <li>Loss of data, profits, reputation, opportunities, or legal claims</li>
                    <li>Damages arising from unauthorized access or security breaches</li>
                    <li>Damages from service interruptions or technical failures</li>
                    <li>Any claims by third parties related to your use of the Website</li>
                  </ul>
                </div>
              </section>

              {/* Section 7 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <Shield className="h-4 w-4 text-primary" />
                  <h3 className="font-semibold text-base">7. USER RESPONSIBILITIES</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>By using LegalCareAI, you agree to:</p>
                  <ul className="list-disc pl-4 space-y-1">
                    <li>Use the platform for lawful purposes only</li>
                    <li>Not misrepresent yourself as a legal professional</li>
                    <li>Not provide advice that could be construed as professional legal counsel</li>
                    <li>Verify all information with qualified professionals before acting</li>
                    <li>Respect the intellectual property rights of others</li>
                    <li>Not upload confidential or privileged information</li>
                    <li>Report any content that violates these terms</li>
                  </ul>
                </div>
              </section>

              {/* Section 8 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <FileText className="h-4 w-4 text-purple-500" />
                  <h3 className="font-semibold text-base">8. PRIVACY & DATA PROTECTION</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>
                    Your use of LegalCareAI is also governed by our Privacy Policy. Please review our Privacy Policy to understand how we collect, use, and protect your information.
                  </p>
                  <ul className="list-disc pl-4 space-y-1">
                    <li>We may collect and process data as described in our Privacy Policy</li>
                    <li>AI interactions may be logged for quality improvement purposes</li>
                    <li>Do not share sensitive personal information in community discussions</li>
                    <li>We implement reasonable security measures but cannot guarantee absolute security</li>
                  </ul>
                </div>
              </section>

              {/* Section 9 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <FileText className="h-4 w-4 text-orange-500" />
                  <h3 className="font-semibold text-base">9. CHANGES TO DISCLAIMER</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>
                    We may update this Disclaimer at any time by posting a revised version on this Website. The "Effective Date" will be updated accordingly. Your continued use of the Website after such changes constitutes acceptance of the revised terms.
                  </p>
                  <p>
                    We encourage you to review this Disclaimer periodically to stay informed of any updates.
                  </p>
                </div>
              </section>

              {/* Section 10 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <MapPin className="h-4 w-4 text-red-500" />
                  <h3 className="font-semibold text-base">10. GOVERNING LAW & JURISDICTION</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>
                    Unless otherwise specified, this Disclaimer and your use of the Website are governed by the laws applicable to the operator of LegalCareAI.com. You agree that any dispute arising from your use of the Website will be subject to the exclusive jurisdiction of courts in the designated jurisdiction.
                  </p>
                </div>
              </section>

              {/* Section 11 */}
              <section className="space-y-3">
                <div className="flex items-center gap-2">
                  <Mail className="h-4 w-4 text-primary" />
                  <h3 className="font-semibold text-base">11. CONTACT INFORMATION</h3>
                </div>
                <div className="pl-6 space-y-2 text-muted-foreground">
                  <p>If you have questions about this Disclaimer or the services provided on this Website, please contact:</p>
                  <div className="bg-muted/50 p-4 rounded-lg space-y-1">
                    <p className="font-semibold text-foreground">LegalCareAI Support</p>
                    <p>Email: <a href="mailto:support@legalcareai.com" className="text-primary hover:underline">support@legalcareai.com</a></p>
                    <p>Website: <a href="https://LegalCareAI.com" className="text-primary hover:underline">https://LegalCareAI.com</a></p>
                  </div>
                </div>
              </section>

              {/* Final Notice */}
              <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-4 mt-6">
                <div className="flex items-start gap-3">
                  <AlertTriangle className="h-5 w-5 text-amber-500 flex-shrink-0 mt-0.5" />
                  <div className="space-y-2">
                    <p className="font-semibold text-foreground">Important Reminder</p>
                    <p className="text-sm text-muted-foreground">
                      By using LegalCareAI, you acknowledge that you have read, understood, and agree to be bound by this Disclaimer. If you do not agree to these terms, please do not use this Website.
                    </p>
                    <p className="text-sm text-muted-foreground">
                      <strong className="text-foreground">Always consult with a qualified legal professional</strong> for advice specific to your situation before making any legal decisions.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </ScrollArea>

          <div className="px-6 py-4 border-t border-border bg-muted/30 flex justify-end">
            <Button onClick={() => setIsOpen(false)} className="gap-2">
              <Shield size={14} />
              I Understand
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default DisclaimerPopup;
